version: '3.8'

services:
  web:
    image: dietsense
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./data:/app/data  # Mount a host directory as a data volume to persist SQLite database
