services:
  web:
    image: dietsense
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    # Remove or comment out the user line if not necessary
    # user: "1000:1000"